#!/bin/bash
set -e
APP_DIR="agentwork-frontend"

echo "Initializing Vite + React + TypeScript project..."
npm create vite@latest "$APP_DIR" -- --template react-ts

cd "$APP_DIR"

# Install dependencies
npm install
npm install -D tailwindcss postcss autoprefixer
npx tailwindcss init -p

# Storybook setup
npx storybook@latest init --builder @storybook/builder-vite

# ESLint & Prettier
npm install -D eslint prettier

# Directory structure
mkdir -p src/components src/pages src/layouts src/hooks src/styles

# Basic README and .gitignore
cat <<'DOC' > README.md
# AgentWork Frontend

Project generated by setup_agentwork.sh.
DOC

npx gitignore node > .gitignore

echo "Setup complete."
